// Vixrex Akıllı Motor server field-contract generator.
//
// TEK KAYNAK: shared/vitrin_alanlari.json
// Bu dosyada elle 46 alan listesi YOKTUR. Amaç, authoritative DB mutation
// migration'ında kullanılacak SQL field contract'ını canonical şemadan
// deterministik üretmektir.
//
// Kullanım:
//   cd public_web
//   npx tsx ../tool/server_field_contract_uret.ts --check
//   npx tsx ../tool/server_field_contract_uret.ts --stdout
//   npx tsx ../tool/server_field_contract_uret.ts --out ../tmp/contract.sql

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface CanonicalField {
  anahtar: string;
  tip: string;
  etiket: string;
  kolon: string;
  bolum: string;
  zorunlu: boolean;
  kalite: boolean;
  minUzunluk: number | null;
  maxUzunluk: number | null;
  min: number | null;
  max: number | null;
  secenekler: string[] | null;
  ipucu: string | null;
  dogrulama: string | null;
  bosDegerler: string[] | null;
}

interface CanonicalSchema {
  _uretim?: string;
  _kaynak?: string;
  alanlar: CanonicalField[];
}

export interface ServerFieldContract {
  fieldKey: string;
  column: string;
  type: string;
  required: boolean;
  minLength: number | null;
  maxLength: number | null;
  min: number | null;
  max: number | null;
  options: string[] | null;
  validation: string | null;
  emptyValues: string[] | null;
}

const moduleDir = dirname(fileURLToPath(import.meta.url));
const canonicalPath = resolve(moduleDir, "../shared/vitrin_alanlari.json");

function readCanonicalSchema(): CanonicalSchema {
  const parsed = JSON.parse(readFileSync(canonicalPath, "utf8")) as CanonicalSchema;
  if (!parsed || !Array.isArray(parsed.alanlar)) {
    throw new Error("INVALID_CANONICAL_FIELD_SCHEMA");
  }
  return parsed;
}

function assertSafeIdentifier(value: string, label: string) {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(value)) {
    throw new Error(`INVALID_${label.toUpperCase()}:${value}`);
  }
}

export function buildServerFieldContracts(
  schema: CanonicalSchema = readCanonicalSchema(),
): ServerFieldContract[] {
  if (schema.alanlar.length !== 46) {
    throw new Error(`FIELD_COUNT_MISMATCH:${schema.alanlar.length}`);
  }

  const keys = new Set<string>();
  const columns = new Set<string>();

  const contracts = schema.alanlar.map((field) => {
    const fieldKey = field.anahtar?.trim();
    const column = field.kolon?.trim();
    const type = field.tip?.trim();

    if (!fieldKey || !column || !type) {
      throw new Error(`INVALID_FIELD_METADATA:${fieldKey || "<empty>"}`);
    }
    assertSafeIdentifier(fieldKey, "field_key");
    assertSafeIdentifier(column, "column");

    if (keys.has(fieldKey)) throw new Error(`DUPLICATE_FIELD_KEY:${fieldKey}`);
    if (columns.has(column)) throw new Error(`DUPLICATE_COLUMN:${column}`);
    keys.add(fieldKey);
    columns.add(column);

    if (
      field.minUzunluk != null &&
      field.maxUzunluk != null &&
      field.minUzunluk > field.maxUzunluk
    ) {
      throw new Error(`INVALID_LENGTH_RANGE:${fieldKey}`);
    }
    if (field.min != null && field.max != null && field.min > field.max) {
      throw new Error(`INVALID_NUMBER_RANGE:${fieldKey}`);
    }

    return {
      fieldKey,
      column,
      type,
      required: field.zorunlu === true,
      minLength: field.minUzunluk ?? null,
      maxLength: field.maxUzunluk ?? null,
      min: field.min ?? null,
      max: field.max ?? null,
      options: field.secenekler ?? null,
      validation: field.dogrulama ?? null,
      emptyValues: field.bosDegerler ?? null,
    } satisfies ServerFieldContract;
  });

  return contracts;
}

function sqlLiteral(value: unknown): string {
  return `'${JSON.stringify(value).replaceAll("'", "''")}'::jsonb`;
}

/**
 * Migration içine alınacak generated lookup function.
 * SECURITY DEFINER değildir; yalnız immutable metadata döndürür.
 * Authoritative mutation RPC authorization/transaction sorumluluğunu ayrıca taşır.
 */
export function generateServerFieldContractSql(
  contracts: ServerFieldContract[] = buildServerFieldContracts(),
): string {
  const cases = contracts
    .map(
      (contract) =>
        `    when '${contract.fieldKey.replaceAll("'", "''")}' then ${sqlLiteral(contract)}`,
    )
    .join("\n");

  return `-- GENERATED by tool/server_field_contract_uret.ts\n-- SOURCE: shared/vitrin_alanlari.json (public_web/src/lib/vitrinFieldSchema.ts)\n-- ELLE DÜZENLEMEYİN.\n\ncreate or replace function public.vixrex_storefront_field_contract(p_field_key text)\nreturns jsonb\nlanguage sql\nimmutable\nset search_path = pg_catalog, public\nas $$\n  select case pg_catalog.btrim(coalesce(p_field_key, ''))\n${cases}\n    else null\n  end;\n$$;\n\ncomment on function public.vixrex_storefront_field_contract(text) is\n  'Generated Vixrex storefront 46-field metadata contract. Canonical source: vitrinFieldSchema.ts.';\n`;
}

function main() {
  const contracts = buildServerFieldContracts();
  const args = process.argv.slice(2);

  if (args.includes("--check")) {
    // buildServerFieldContracts zaten count/unique/range/identifier kontrollerini yaptı.
    console.log(`server field contract OK: ${contracts.length}/46`);
    return;
  }

  const sql = generateServerFieldContractSql(contracts);
  if (args.includes("--stdout")) {
    process.stdout.write(sql);
    return;
  }

  const outIndex = args.indexOf("--out");
  if (outIndex >= 0) {
    const out = args[outIndex + 1];
    if (!out) throw new Error("MISSING_OUT_PATH");
    writeFileSync(resolve(process.cwd(), out), sql, "utf8");
    console.log(`server field contract yazıldı: ${out}`);
    return;
  }

  console.log("Kullanım: --check | --stdout | --out <path>");
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : null;
if (invokedPath === fileURLToPath(import.meta.url)) {
  main();
}
