// ÜRETİLMİŞ DOSYA — ELLE DÜZENLEME.
// Kaynak: shared/vixrex_matcher_contract.json

const int vixrexMatcherMinInflectedAliasLength = 5;
const List<String> vixrexMatcherSafeSuffixes = [
  'm',
  'im',
  'um',
  'n',
  'in',
  'un',
  'i',
  'u',
  'mi',
  'mu',
  'imi',
  'umu',
  'me',
  'ma',
  'ime',
  'uma',
  'ni',
  'nu',
  'ini',
  'unu',
  'ne',
  'na',
  'ine',
  'una',
  'min',
  'mun',
  'imin',
  'umun',
  'nin',
  'nun',
  'inin',
  'unun',
  'mde',
  'mda',
  'mden',
  'mdan',
  'imde',
  'imda',
  'imden',
  'imdan',
  'umde',
  'umda',
  'umden',
  'umdan',
  'nde',
  'nda',
  'nden',
  'ndan',
  'inde',
  'inda',
  'inden',
  'indan',
  'unda',
  'unde',
  'undan',
  'unden',
  'yi',
  'yu',
  'ye',
  'ya',
  'yim',
  'yum',
  'yin',
  'yun',
];
const Map<String, List<String>> vixrexMatcherExactFormsByField = {
  'il': ['ili'],
  'ilce': ['ilceyi', 'ilcemi'],
  'mahalle': ['mahalleyi', 'mahallemi', 'semti', 'semtimi'],
  'logo': ['logoyu', 'logomu'],
  'isletmeTuru': ['turunu', 'turumu'],
  'website': ['sitemi', 'siteyi', 'websiteyi'],
  'puanGoster': ['puani', 'puanlari'],
  'kapakGorseli': ['kapagi', 'kapagini'],
};
