// ÜRETİLMİŞ DOSYA — ELLE DÜZENLEME.
// Kaynak : shared/vixrex_niyet_sozlugu.json

class VixrexNiyetAlan {
  final String anahtar;
  final String etiket;
  final String tip;
  final String kolon;
  final String bolum;
  final String beklenenVeriTipi;
  final List<String> esAnlamlar;
  final List<String> ornekIfadeler;
  const VixrexNiyetAlan({required this.anahtar,required this.etiket,required this.tip,required this.kolon,required this.bolum,required this.beklenenVeriTipi,required this.esAnlamlar,required this.ornekIfadeler,});
}
const List<VixrexNiyetAlan> vixrexNiyetSozlugu = [
  VixrexNiyetAlan(
    anahtar: 'isletmeAdi',
    etiket: 'İşletme Adı',
    tip: 'metin',
    kolon: 'name',
    bolum: 'hero',
    beklenenVeriTipi: 'metin (2-60 karakter)',
    esAnlamlar: ['işletme adı', 'dükkan adı', 'mağaza adı', 'firma adı', 'iş yeri adı', 'şirket adı', 'marka adı', 'isim'],
    ornekIfadeler: ['İşletme adını \'Aymira Giyim\' yap', 'Dükkan adını değiştir: {deger}', 'Mağazamın adı {deger} olsun', 'İşletme adımı güncelle {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'heroRozet',
    etiket: 'Hero Rozet Metni',
    tip: 'metin',
    kolon: 'hero_badge',
    bolum: 'hero',
    beklenenVeriTipi: 'metin (0-60 karakter, kalite)',
    esAnlamlar: ['rozet', 'hero rozet', 'üst rozet', 'küçük etiket', 'vurgu metni', 'rozet metni', 'badge'],
    ornekIfadeler: ['Rozeti \'Kadıköy\'ün En İyisi\' yap', 'Hero rozetini {deger} olarak güncelle', 'Üstteki küçük yazıyı {deger} yap', 'Rozet metnini ekle: {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'kisaTanitim',
    etiket: 'Kısa Tanıtım',
    tip: 'uzunMetin',
    kolon: 'description',
    bolum: 'hero',
    beklenenVeriTipi: 'uzunMetin (0-300 karakter)',
    esAnlamlar: ['kısa tanıtım', 'tanıtım', 'açıklama', 'özet', 'hakkında kısa', 'işletme açıklaması', 'tanıtım yazısı'],
    ornekIfadeler: ['Kısa tanıtımı {deger} yap', 'Açıklamayı ekle: {deger}', 'Tanıtım yazısını değiştir {deger}', 'Özet kısmını {deger} olarak güncelle'],
  ),
  VixrexNiyetAlan(
    anahtar: 'konumMetni',
    etiket: 'Hero Konum Metni',
    tip: 'metin',
    kolon: 'hero_location_text',
    bolum: 'hero',
    beklenenVeriTipi: 'metin (0-60 karakter)',
    esAnlamlar: ['konum metni', 'hero konum', 'üst konum', 'konum yazısı', 'yer metni', 'semt yazısı'],
    ornekIfadeler: ['Konum metnini \'Kadıköy, İstanbul\' yap', 'Hero konumunu {deger} olarak değiştir', 'Üstteki konum yazısını {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'kategori',
    etiket: 'İşletme Kategorisi',
    tip: 'secim',
    kolon: 'kategori',
    bolum: 'hero',
    beklenenVeriTipi: 'secim (Giyim, Butik, Gıda, Fırın, Kozmetik, Dekorasyon, Elektronik, Kırtasiye, Kafe / Lokanta, Kuaför, Teknik Servis, Danışmanlık, Eğitim, Ev Temizlik, Spor / Fitness, Pet / Veteriner, Sağlık / Yaşam, Oto / Araç, Diğer)',
    esAnlamlar: ['kategori', 'işletme kategorisi', 'sektör', 'faaliyet alanı', 'iş kolu', 'tür', 'alan'],
    ornekIfadeler: ['Kategorimi Kuaför yap', 'Sektörümü {deger} olarak değiştir', 'İşletme kategorisini {deger} seç', 'Kategori {deger} olsun'],
  ),
  VixrexNiyetAlan(
    anahtar: 'isletmeTuru',
    etiket: 'İşletme Türü',
    tip: 'metin',
    kolon: 'business_type',
    bolum: 'hero',
    beklenenVeriTipi: 'metin (0-40 karakter)',
    esAnlamlar: ['işletme türü', 'firma türü', 'iş türü', 'dükkan türü', 'çalışma alanı detayı'],
    ornekIfadeler: ['İşletme türünü \'Erkek Kuaförü\' yap', 'Türünü {deger} olarak güncelle', 'İşletme türümü değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'logo',
    etiket: 'Logo',
    tip: 'gorsel',
    kolon: 'logo_url',
    bolum: 'hero',
    beklenenVeriTipi: 'gorsel (https URL, kalite)',
    esAnlamlar: ['logo', 'marka logosu', 'amblem', 'kurumsal logo', 'işletme logosu'],
    ornekIfadeler: ['Logoyu {deger} yap', 'Logo ekle: {deger}', 'Logomu değiştir {deger}', 'Amblemi güncelle {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'kapakGorseli',
    etiket: 'Kapak / Hero Görseli',
    tip: 'gorsel',
    kolon: 'shelf_image_url',
    bolum: 'hero',
    beklenenVeriTipi: 'gorsel (https URL, kalite)',
    esAnlamlar: ['kapak görseli', 'kapak fotoğrafı', 'hero görseli', 'üst görsel', 'kapak resmi', 'vitrin fotoğrafı', 'banner görseli'],
    ornekIfadeler: ['Kapak görselini {deger} yap', 'Kapak fotoğrafını değiştir {deger}', 'Hero görselini ekle {deger}', 'Vitrin fotoğrafını {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'whatsapp',
    etiket: 'WhatsApp Numarası',
    tip: 'telefon',
    kolon: 'whatsapp',
    bolum: 'contact',
    beklenenVeriTipi: 'telefon (tr_mobil: 05xx xxx xx xx → 905xxxxxxxxx, zorunlu)',
    esAnlamlar: ['whatsapp', 'whatsapp numarası', 'cep numarası', 'telefon whatsapp', 'iletişim numarası', 'gsm', 'whatsapp hattı'],
    ornekIfadeler: ['WhatsApp numaramı 0555 123 45 67 yap', 'WhatsApp\'ı {deger} olarak güncelle', 'İletişim numaramı {deger} yap', 'Whatsapp hattımı değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'telefon',
    etiket: 'Telefon',
    tip: 'telefon',
    kolon: 'phone',
    bolum: 'contact',
    beklenenVeriTipi: 'telefon (10-13 rakam)',
    esAnlamlar: ['telefon', 'sabit telefon', 'iş telefonu', 'dükkan telefonu', 'tel', 'arama numarası'],
    ornekIfadeler: ['Telefonu {deger} yap', 'Sabit telefonumu {deger} olarak ekle', 'İş telefonunu değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'eposta',
    etiket: 'E-posta',
    tip: 'eposta',
    kolon: 'email',
    bolum: 'contact',
    beklenenVeriTipi: 'eposta (max 120, ornek@adres.com)',
    esAnlamlar: ['e-posta', 'eposta', 'mail', 'e-mail', 'elektronik posta', 'mail adresi'],
    ornekIfadeler: ['E-postamı {deger} yap', 'Mail adresimi {deger} olarak güncelle', 'Epostayı değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'adres',
    etiket: 'Açık Adres',
    tip: 'uzunMetin',
    kolon: 'address',
    bolum: 'contact',
    beklenenVeriTipi: 'uzunMetin (zorunlu, max 200, en az sokak/cadde + numara, AddressValidator)',
    esAnlamlar: ['adres', 'açık adres', 'dükkan adresi', 'iş yeri adresi', 'konum adresi', 'işletme adresi'],
    ornekIfadeler: ['Adresimi \'Atatürk Cad. No:24\' yap', 'Açık adresi {deger} olarak değiştir', 'Dükkan adresini güncelle {deger}', 'Adresi {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'il',
    etiket: 'İl',
    tip: 'metin',
    kolon: 'province_name',
    bolum: 'contact',
    beklenenVeriTipi: 'metin (zorunlu, max 60)',
    esAnlamlar: ['il', 'şehir', 'kent', 'bulunduğum il'],
    ornekIfadeler: ['İli İstanbul yap', 'Şehrimi {deger} olarak değiştir', 'İl {deger} olsun'],
  ),
  VixrexNiyetAlan(
    anahtar: 'ilce',
    etiket: 'İlçe',
    tip: 'metin',
    kolon: 'district_name',
    bolum: 'contact',
    beklenenVeriTipi: 'metin (zorunlu, max 60)',
    esAnlamlar: ['ilçe', 'semt ilçesi', 'ilçe adı'],
    ornekIfadeler: ['İlçeyi Kadıköy yap', 'İlçemi {deger} olarak güncelle', 'İlçe {deger} olsun'],
  ),
  VixrexNiyetAlan(
    anahtar: 'mahalle',
    etiket: 'Mahalle',
    tip: 'metin',
    kolon: 'neighborhood_name',
    bolum: 'contact',
    beklenenVeriTipi: 'metin (max 60, kalite)',
    esAnlamlar: ['mahalle', 'semt', 'bölge', 'mıntıka'],
    ornekIfadeler: ['Mahalleyi Caddebostan yap', 'Mahallemi {deger} olarak değiştir', 'Semti {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'haritaEtiketi',
    etiket: 'Harita Kartı Etiketi',
    tip: 'metin',
    kolon: 'map_label',
    bolum: 'contact',
    beklenenVeriTipi: 'metin (max 120)',
    esAnlamlar: ['harita etiketi', 'harita notu', 'harita kartı yazısı', 'harita açıklaması'],
    ornekIfadeler: ['Harita etiketini \'Çarşı içi, otopark var\' yap', 'Harita notunu {deger} olarak güncelle'],
  ),
  VixrexNiyetAlan(
    anahtar: 'calismaSaatleri',
    etiket: 'Çalışma Saatleri',
    tip: 'metin',
    kolon: 'working_hours',
    bolum: 'contact',
    beklenenVeriTipi: 'metin (max 400, kalite)',
    esAnlamlar: ['çalışma saatleri', 'açılış saatleri', 'mesai saatleri', 'açık olduğumuz saatler', 'çalışma zamanı', 'saatler'],
    ornekIfadeler: ['Çalışma saatlerini \'09:00-18:00\' yap', 'Saatleri {deger} olarak değiştir', 'Mesai saatlerimi güncelle {deger}', 'Açılış saatlerini {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'instagram',
    etiket: 'Instagram Kullanıcı Adı',
    tip: 'metin',
    kolon: 'instagram',
    bolum: 'contact',
    beklenenVeriTipi: 'metin (max 30, @ olmadan)',
    esAnlamlar: ['instagram', 'insta', 'instagram adı', 'instagram kullanıcı adı', 'ig'],
    ornekIfadeler: ['Instagramı aymiragiyim yap', 'Insta adımı {deger} olarak güncelle', 'Instagram kullanıcı adımı {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'website',
    etiket: 'Web Sitesi',
    tip: 'url',
    kolon: 'website',
    bolum: 'contact',
    beklenenVeriTipi: 'url (https://...)',
    esAnlamlar: ['web sitesi', 'website', 'site', 'internet sitesi', 'web adresi', 'url'],
    ornekIfadeler: ['Web sitemi https://aymira.com yap', 'Site adresini {deger} olarak ekle', 'Websiteyi {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'haritaLinki',
    etiket: 'Google İşletme / Harita Bağlantısı',
    tip: 'url',
    kolon: 'google_business_link',
    bolum: 'contact',
    beklenenVeriTipi: 'url (https://..., kalite)',
    esAnlamlar: ['harita linki', 'google linki', 'harita bağlantısı', 'google işletme linki', 'maps linki', 'konum linki', 'yol tarifi linki'],
    ornekIfadeler: ['Harita linkini {deger} yap', 'Google linkimi {deger} olarak ekle', 'Maps bağlantısını {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'enlem',
    etiket: 'Konum — Enlem',
    tip: 'sayi',
    kolon: 'latitude',
    bolum: 'contact',
    beklenenVeriTipi: 'sayi (-90..90)',
    esAnlamlar: ['enlem', 'latitude', 'koordinat enlem', 'yatay konum'],
    ornekIfadeler: ['Enlemi 41.025 yap', 'Latitude {deger} olsun', 'Enlem değerini {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'boylam',
    etiket: 'Konum — Boylam',
    tip: 'sayi',
    kolon: 'longitude',
    bolum: 'contact',
    beklenenVeriTipi: 'sayi (-180..180)',
    esAnlamlar: ['boylam', 'longitude', 'koordinat boylam', 'dikey konum'],
    ornekIfadeler: ['Boylamı 29.05 yap', 'Longitude {deger} olsun', 'Boylam değerini {deger} yap'],
  ),
  VixrexNiyetAlan(
    anahtar: 'kategoriBolumBaslik',
    etiket: 'Kategori Bölümü Başlığı',
    tip: 'metin',
    kolon: 'category_section_title',
    bolum: 'categories',
    beklenenVeriTipi: 'metin (max 60)',
    esAnlamlar: ['kategori başlığı', 'kategori bölüm başlığı', 'kategoriler başlığı'],
    ornekIfadeler: ['Kategori başlığını {deger} yap', 'Kategori bölüm başlığını değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'urunBolumBaslik',
    etiket: 'Ürün Bölümü Başlığı',
    tip: 'metin',
    kolon: 'product_section_title',
    bolum: 'products',
    beklenenVeriTipi: 'metin (max 60)',
    esAnlamlar: ['ürün başlığı', 'ürün bölüm başlığı', 'ürünler başlığı', 'menü başlığı'],
    ornekIfadeler: ['Ürün başlığını {deger} yap', 'Ürün bölüm başlığını {deger} olarak güncelle'],
  ),
  VixrexNiyetAlan(
    anahtar: 'bantEtiket',
    etiket: 'Kampanya Etiketi',
    tip: 'metin',
    kolon: 'featured_banner_label',
    bolum: 'featured',
    beklenenVeriTipi: 'metin (max 40)',
    esAnlamlar: ['kampanya etiketi', 'bant etiketi', 'etiket', 'kampanya rozeti', 'öne çıkan etiket'],
    ornekIfadeler: ['Kampanya etiketini \'Bu haftaya özel\' yap', 'Bant etiketini {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'bantBaslik',
    etiket: 'Kampanya Başlığı',
    tip: 'metin',
    kolon: 'featured_banner_title',
    bolum: 'featured',
    beklenenVeriTipi: 'metin (max 90)',
    esAnlamlar: ['kampanya başlığı', 'bant başlığı', 'öne çıkan başlık', 'kampanya adı'],
    ornekIfadeler: ['Kampanya başlığını {deger} yap', 'Bant başlığını değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'bantAciklama',
    etiket: 'Kampanya Açıklaması',
    tip: 'uzunMetin',
    kolon: 'featured_banner_description',
    bolum: 'featured',
    beklenenVeriTipi: 'uzunMetin (max 200)',
    esAnlamlar: ['kampanya açıklaması', 'bant açıklaması', 'kampanya detayı', 'öne çıkan açıklama'],
    ornekIfadeler: ['Kampanya açıklamasını {deger} yap', 'Bant açıklamasını değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'bantGorsel',
    etiket: 'Kampanya Görseli',
    tip: 'gorsel',
    kolon: 'featured_banner_image_url',
    bolum: 'featured',
    beklenenVeriTipi: 'gorsel (https URL)',
    esAnlamlar: ['kampanya görseli', 'bant görseli', 'kampanya fotoğrafı', 'öne çıkan görsel', 'banner resmi'],
    ornekIfadeler: ['Kampanya görselini {deger} yap', 'Bant görselini değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'bantFiyat',
    etiket: 'Kampanya Fiyat Metni',
    tip: 'metin',
    kolon: 'featured_banner_price_text',
    bolum: 'featured',
    beklenenVeriTipi: 'metin (max 30)',
    esAnlamlar: ['kampanya fiyatı', 'bant fiyatı', 'fiyat metni', 'kampanya fiyat yazısı'],
    ornekIfadeler: ['Kampanya fiyatını \'499 TL\' yap', 'Bant fiyatını {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'hakkindaUstBaslik',
    etiket: 'Hakkımızda Üst Başlık',
    tip: 'metin',
    kolon: 'about_kicker',
    bolum: 'about',
    beklenenVeriTipi: 'metin (max 40)',
    esAnlamlar: ['hakkımızda üst başlık', 'hakkında üst yazı', 'about kicker', 'üst başlık hakkında'],
    ornekIfadeler: ['Hakkımızda üst başlığı {deger} yap', 'About kicker\'ı {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'hakkindaBaslik',
    etiket: 'Hakkımızda Başlığı',
    tip: 'metin',
    kolon: 'about_title',
    bolum: 'about',
    beklenenVeriTipi: 'metin (max 90, kalite)',
    esAnlamlar: ['hakkımızda başlığı', 'hakkında başlık', 'biz kimiz başlığı', 'hakkımızda başlık'],
    ornekIfadeler: ['Hakkımızda başlığını {deger} yap', 'Hakkında başlığı değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'hakkindaMetin',
    etiket: 'Hakkımızda Yazısı',
    tip: 'uzunMetin',
    kolon: 'corporate_bio',
    bolum: 'about',
    beklenenVeriTipi: 'uzunMetin (max 1200, kalite)',
    esAnlamlar: ['hakkımızda yazısı', 'hakkımızda metni', 'hikayemiz', 'biz kimiz yazısı', 'kurumsal yazı', 'hakkında metni', 'işletme hikayesi'],
    ornekIfadeler: ['Hakkımızda yazısını {deger} yap', 'Hikayemizi ekle: {deger}', 'Hakkımızda metnini değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'hakkindaGorsel',
    etiket: 'Hakkımızda Görseli',
    tip: 'gorsel',
    kolon: 'about_image_url',
    bolum: 'about',
    beklenenVeriTipi: 'gorsel (https URL)',
    esAnlamlar: ['hakkımızda görseli', 'hakkında görseli', 'hakkımızda fotoğrafı', 'bizim fotoğraf', 'ekip fotoğrafı', 'dükkan fotoğrafı hakkında'],
    ornekIfadeler: ['Hakkımızda görselini {deger} yap', 'Hakkında fotoğrafını {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'hakkindaGorselAlt',
    etiket: 'Görsel Alt Yazısı',
    tip: 'metin',
    kolon: 'about_image_caption',
    bolum: 'about',
    beklenenVeriTipi: 'metin (max 120)',
    esAnlamlar: ['görsel alt yazısı', 'fotoğraf alt yazısı', 'resim altı yazısı', 'hakkımızda görsel altı'],
    ornekIfadeler: ['Görsel alt yazısını {deger} yap', 'Fotoğraf altı yazısını {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'galeriUstBaslik',
    etiket: 'Galeri Üst Başlık',
    tip: 'metin',
    kolon: 'gallery_section_kicker',
    bolum: 'gallery',
    beklenenVeriTipi: 'metin (max 40)',
    esAnlamlar: ['galeri üst başlık', 'galeri kicker', 'galeri üst yazısı'],
    ornekIfadeler: ['Galeri üst başlığı {deger} yap', 'Galeri kicker\'ı {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'galeriBaslik',
    etiket: 'Galeri Başlığı',
    tip: 'metin',
    kolon: 'gallery_section_title',
    bolum: 'gallery',
    beklenenVeriTipi: 'metin (max 90)',
    esAnlamlar: ['galeri başlığı', 'galeri başlık', 'fotoğraf galerisi başlığı', 'resim galerisi başlığı'],
    ornekIfadeler: ['Galeri başlığını {deger} yap', 'Galeri başlığını değiştir {deger}'],
  ),
  VixrexNiyetAlan(
    anahtar: 'galeriAksiyonMetni',
    etiket: 'Galeri Buton Metni',
    tip: 'metin',
    kolon: 'gallery_action_label',
    bolum: 'gallery',
    beklenenVeriTipi: 'metin (max 40)',
    esAnlamlar: ['galeri buton metni', 'galeri buton yazısı', 'galeri düğme metni', 'galeri aksiyon metni'],
    ornekIfadeler: ['Galeri buton metnini {deger} yap', 'Galeri düğme yazısını {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'galeriAksiyonLinki',
    etiket: 'Galeri Buton Bağlantısı',
    tip: 'url',
    kolon: 'gallery_action_href',
    bolum: 'gallery',
    beklenenVeriTipi: 'url (https:// veya #)',
    esAnlamlar: ['galeri buton linki', 'galeri bağlantısı', 'galeri buton bağlantısı', 'galeri linki'],
    ornekIfadeler: ['Galeri buton linkini {deger} yap', 'Galeri bağlantısını {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'blogUstBaslik',
    etiket: 'Blog Üst Başlık',
    tip: 'metin',
    kolon: 'blog_section_kicker',
    bolum: 'blog',
    beklenenVeriTipi: 'metin (max 40)',
    esAnlamlar: ['blog üst başlık', 'yazılar üst başlık', 'blog kicker'],
    ornekIfadeler: ['Blog üst başlığı {deger} yap', 'Blog kicker\'ı {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'blogBaslik',
    etiket: 'Blog Bölüm Başlığı',
    tip: 'metin',
    kolon: 'blog_section_title',
    bolum: 'blog',
    beklenenVeriTipi: 'metin (max 90)',
    esAnlamlar: ['blog başlığı', 'yazılar başlığı', 'blog bölüm başlığı'],
    ornekIfadeler: ['Blog başlığını {deger} yap', 'Blog bölüm başlığını {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'sssUstBaslik',
    etiket: 'SSS Üst Başlık',
    tip: 'metin',
    kolon: 'faq_section_kicker',
    bolum: 'faq',
    beklenenVeriTipi: 'metin (max 40)',
    esAnlamlar: ['sss üst başlık', 'sss kicker', 'sorular üst başlık', 'sık sorulan sorular üst'],
    ornekIfadeler: ['SSS üst başlığı {deger} yap', 'SSS kicker\'ı {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'sssBaslik',
    etiket: 'SSS Bölüm Başlığı',
    tip: 'metin',
    kolon: 'faq_section_title',
    bolum: 'faq',
    beklenenVeriTipi: 'metin (max 90)',
    esAnlamlar: ['sss başlığı', 'sss bölüm başlığı', 'sık sorulan sorular başlığı', 'sorular başlığı'],
    ornekIfadeler: ['SSS başlığını {deger} yap', 'SSS bölüm başlığını {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'sssAciklama',
    etiket: 'SSS Bölüm Açıklaması',
    tip: 'uzunMetin',
    kolon: 'faq_section_description',
    bolum: 'faq',
    beklenenVeriTipi: 'uzunMetin (max 200)',
    esAnlamlar: ['sss açıklaması', 'sss açıklama', 'sık sorulan sorular açıklaması', 'sorular açıklaması'],
    ornekIfadeler: ['SSS açıklamasını {deger} yap', 'SSS bölüm açıklamasını {deger} olarak değiştir'],
  ),
  VixrexNiyetAlan(
    anahtar: 'puanGoster',
    etiket: 'Değerlendirme Puanını Göster',
    tip: 'acikKapali',
    kolon: 'show_storefront_rating',
    bolum: 'hero',
    beklenenVeriTipi: 'acikKapali (true/false, açık/kapalı, göster/gizle)',
    esAnlamlar: ['puan göster', 'değerlendirme puanı', 'puanı göster', 'rating göster', 'yıldız puanı göster'],
    ornekIfadeler: ['Puanı göster', 'Puanı gizle', 'Değerlendirme puanını aç', 'Rating\'i kapat'],
  ),
  VixrexNiyetAlan(
    anahtar: 'yolTarifiGoster',
    etiket: 'Yol Tarifi Butonunu Göster',
    tip: 'acikKapali',
    kolon: 'show_directions_link',
    bolum: 'contact',
    beklenenVeriTipi: 'acikKapali (true/false)',
    esAnlamlar: ['yol tarifi göster', 'yol tarifi butonu', 'haritada yol tarifi', 'navigasyon göster', 'yol tarifi', 'yol tarifini'],
    ornekIfadeler: ['Yol tarifini göster', 'Yol tarifi butonunu gizle', 'Yol tarifini aç', 'Navigasyonu kapat'],
  ),
  VixrexNiyetAlan(
    anahtar: 'referansLinki',
    etiket: 'Referanslar Bağlantısı',
    tip: 'url',
    kolon: 'references_link',
    bolum: 'about',
    beklenenVeriTipi: 'url (https://...)',
    esAnlamlar: ['referans linki', 'referans bağlantısı', 'referanslar linki', 'müşteri yorum linki'],
    ornekIfadeler: ['Referans linkini {deger} yap', 'Referans bağlantısını {deger} olarak değiştir'],
  ),
];
final Map<String, VixrexNiyetAlan> vixrexNiyetAlanByAnahtar = { for (final a in vixrexNiyetSozlugu) a.anahtar: a, };