-- Kiralik demo vitrinlerin urunlerini yeni sema (surum 4) ile doldur.
-- Kart ve form artik kategoriye ozel alanlari istiyor; demo urunlerde bu
-- alanlar bos oldugu icin kiralayan esnaf ilk duzenlemede duvara carpiyordu.

-- Kategori sablonlarini yeni bolunmus sablonlara tasi.
update public.product_categories c set product_template_key = 'cafe_restaurant'
from public.stores s where s.id = c.store_id and s.slug = 'kiralik-kafe';

update public.product_categories c set product_template_key = 'technical_service'
from public.stores s where s.id = c.store_id
  and s.slug in ('kiralik-teknik','demo-teknofix')
  and c.name not in ('Aksesuar','Aksesuar & Yedek Parça');

-- Aksesuar kategorileri hizmet degil, satilan urun.
update public.product_categories c set product_template_key = 'electronics'
from public.stores s where s.id = c.store_id
  and s.slug in ('kiralik-teknik','demo-teknofix')
  and c.name in ('Aksesuar','Aksesuar & Yedek Parça');

-- Urun detaylari
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"service","attributes":[],"service":{"serviceType":"Saç kesimi","durationMinutes":45,"priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kuafor' and p.name = 'Saç Kesimi & Yıkama';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"service","attributes":[],"service":{"serviceType":"Saç bakımı","durationMinutes":120,"priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kuafor' and p.name = 'Keratin Bakımı';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"service","attributes":[],"service":{"serviceType":"Saç boyama","durationMinutes":90,"priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kuafor' and p.name = 'Komple Saç Boyama';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"service","attributes":[],"service":{"serviceType":"Saç boyama","durationMinutes":150,"priceMode":"starting_from","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kuafor' and p.name = 'Balyaj & Ombre';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"service","attributes":[],"service":{"serviceType":"Makyaj","durationMinutes":60,"priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kuafor' and p.name = 'Gece Makyajı';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"service","attributes":[],"service":{"serviceType":"Tırnak bakımı","durationMinutes":75,"priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kuafor' and p.name = 'Manikür & Pedikür';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Apple iPhone"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":6},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":1}],"service":{"serviceType":"Ekran değişimi","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-teknik' and p.name = 'iPhone Ekran Değişimi';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Samsung Galaxy"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":6},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":1}],"service":{"serviceType":"Ekran değişimi","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-teknik' and p.name = 'Samsung Ekran Değişimi';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Apple / Samsung"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":12},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":1}],"service":{"serviceType":"Batarya değişimi","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-teknik' and p.name = 'Batarya Yenileme';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Windows / macOS"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":3},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"haric"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":1}],"service":{"serviceType":"Yazılım / kurulum","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-teknik' and p.name = 'Laptop Format & Kurulum';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Laptop (tüm markalar)"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":6},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":2}],"service":{"serviceType":"Periyodik bakım","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-teknik' and p.name = 'Fan & Termal Bakımı';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Apple iPhone"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":12},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":1}],"service":{"serviceType":"Ekran değişimi","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'demo-teknofix' and p.name = 'iPhone Orijinal Ekran Değişimi';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Apple MacBook"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":12},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":3}],"service":{"serviceType":"Ekran değişimi","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'demo-teknofix' and p.name = 'MacBook Klavye & Tuş Takımı Değişimi';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Apple iPad"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":12},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":2}],"service":{"serviceType":"Ekran değişimi","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'demo-teknofix' and p.name = 'iPad Ekran Değişimi';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Laptop (tüm markalar)"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":6},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"duruma_gore"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":5}],"service":{"serviceType":"Anakart onarımı","priceMode":"starting_from","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'demo-teknofix' and p.name = 'Laptop Anakart Arıza Tespiti & Onarımı';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Samsung Galaxy"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":12},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":1}],"service":{"serviceType":"Batarya değişimi","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'demo-teknofix' and p.name = 'Samsung Galaxy Batarya Değişimi';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"HDD / SSD"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":0},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"haric"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":5}],"service":{"serviceType":"Veri kurtarma","priceMode":"starting_from","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'demo-teknofix' and p.name = 'Data Kurtarma (HDD/SSD)';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"service","templateKey":"technical_service","attributes":[{"key":"deviceBrandModel","label":"Cihaz marka / model","value":"Apple / Samsung"},{"key":"warrantyMonths","label":"Garanti süresi (ay)","value":6},{"key":"partsIncluded","label":"Parça fiyata dahil mi","value":"dahil"},{"key":"deliveryDays","label":"Teslim süresi (gün)","value":1}],"service":{"serviceType":"Ekran değişimi","priceMode":"fixed","serviceLocation":"business"}}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'demo-teknofix' and p.name = 'Telefon Kamera Modülü Değişimi';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"fashion","attributes":[{"key":"color","label":"Renk","value":"Camel"},{"key":"size","label":"Beden","value":"S-XL"},{"key":"gender","label":"Cinsiyet","value":"kadin"},{"key":"fit","label":"Kalıp / kesim","value":"normal"},{"key":"material","label":"Materyal","value":"%100 yün karışımı"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-butik' and p.name = 'Sonbahar Trençkot';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"fashion","attributes":[{"key":"color","label":"Renk","value":"Krem"},{"key":"size","label":"Beden","value":"S-XXL"},{"key":"gender","label":"Cinsiyet","value":"unisex"},{"key":"fit","label":"Kalıp / kesim","value":"normal"},{"key":"material","label":"Materyal","value":"%100 keten"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-butik' and p.name = 'Günlük Keten Gömlek';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"fashion","attributes":[{"key":"color","label":"Renk","value":"Açık mavi"},{"key":"size","label":"Beden","value":"S-XL"},{"key":"gender","label":"Cinsiyet","value":"kadin"},{"key":"fit","label":"Kalıp / kesim","value":"bol"},{"key":"material","label":"Materyal","value":"Bambu karışımı"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-butik' and p.name = 'Bambu Pijama Takımı';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"fashion","attributes":[{"key":"color","label":"Renk","value":"Taba"},{"key":"size","label":"Beden","value":"Tek ebat"},{"key":"gender","label":"Cinsiyet","value":"kadin"},{"key":"fit","label":"Kalıp / kesim","value":"normal"},{"key":"material","label":"Materyal","value":"Tam grain İtalyan derisi"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-butik' and p.name = 'El Yapımı Deri Çanta';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"fashion","attributes":[{"key":"color","label":"Renk","value":"Desenli"},{"key":"size","label":"Beden","value":"90x90 cm"},{"key":"gender","label":"Cinsiyet","value":"kadin"},{"key":"fit","label":"Kalıp / kesim","value":"normal"},{"key":"material","label":"Materyal","value":"%100 doğal ipek"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-butik' and p.name = 'İpek Fular';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"fashion","attributes":[{"key":"color","label":"Renk","value":"Siyah"},{"key":"size","label":"Beden","value":"S-L"},{"key":"gender","label":"Cinsiyet","value":"kadin"},{"key":"fit","label":"Kalıp / kesim","value":"dar"},{"key":"material","label":"Materyal","value":"Viskon karışımı"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-butik' and p.name = 'Kapsül Sezon Elbise';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"cafe_restaurant","attributes":[{"key":"portion","label":"Porsiyon","value":"250 ml"},{"key":"allergens","label":"Alerjen bilgisi","value":[]},{"key":"mainIngredients","label":"Temel bileşenler","value":["Etiyopya kahve çekirdeği","Su"]},{"key":"containsAlcoholPork","label":"Alkol / domuz türevi içerir","value":"yok"},{"key":"prepMinutes","label":"Hazırlama süresi (dakika)","value":5}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kafe' and p.name = 'Filtre Kahve (V60)';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"cafe_restaurant","attributes":[{"key":"portion","label":"Porsiyon","value":"330 ml"},{"key":"allergens","label":"Alerjen bilgisi","value":[]},{"key":"mainIngredients","label":"Temel bileşenler","value":["Kahve çekirdeği","Su"]},{"key":"containsAlcoholPork","label":"Alkol / domuz türevi içerir","value":"yok"},{"key":"prepMinutes","label":"Hazırlama süresi (dakika)","value":3}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kafe' and p.name = 'Cold Brew';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"cafe_restaurant","attributes":[{"key":"portion","label":"Porsiyon","value":"1 dilim"},{"key":"allergens","label":"Alerjen bilgisi","value":["Gluten","Süt","Yumurta"]},{"key":"mainIngredients","label":"Temel bileşenler","value":["Mascarpone","Kedidili","Kahve","Kakao"]},{"key":"containsAlcoholPork","label":"Alkol / domuz türevi içerir","value":"yok"},{"key":"prepMinutes","label":"Hazırlama süresi (dakika)","value":5}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kafe' and p.name = 'Tiramisu (Ev Yapımı)';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"cafe_restaurant","attributes":[{"key":"portion","label":"Porsiyon","value":"1 dilim"},{"key":"allergens","label":"Alerjen bilgisi","value":["Gluten","Süt","Yumurta"]},{"key":"mainIngredients","label":"Temel bileşenler","value":["Bitter çikolata","Un","Orman meyvesi"]},{"key":"containsAlcoholPork","label":"Alkol / domuz türevi içerir","value":"yok"},{"key":"prepMinutes","label":"Hazırlama süresi (dakika)","value":5}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kafe' and p.name = 'Çikolatalı Kek';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"cafe_restaurant","attributes":[{"key":"portion","label":"Porsiyon","value":"1 porsiyon"},{"key":"allergens","label":"Alerjen bilgisi","value":["Gluten","Yumurta"]},{"key":"mainIngredients","label":"Temel bileşenler","value":["Ekşi mayalı ekmek","Avokado","Poşe yumurta"]},{"key":"containsAlcoholPork","label":"Alkol / domuz türevi içerir","value":"yok"},{"key":"prepMinutes","label":"Hazırlama süresi (dakika)","value":10}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kafe' and p.name = 'Avokado Toast';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"cafe_restaurant","attributes":[{"key":"portion","label":"Porsiyon","value":"1 porsiyon"},{"key":"allergens","label":"Alerjen bilgisi","value":["Gluten","Süt"]},{"key":"mainIngredients","label":"Temel bileşenler","value":["Ekmek","Kaşar","Domates","Roka"]},{"key":"containsAlcoholPork","label":"Alkol / domuz türevi içerir","value":"yok"},{"key":"prepMinutes","label":"Hazırlama süresi (dakika)","value":8}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-kafe' and p.name = 'Kaşarlı Tost';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"food","attributes":[{"key":"netQuantity","label":"Net miktar","value":"yaklaşık 5 kg"},{"key":"unitPrice","label":"Birim fiyat","value":"33 TL/kg"},{"key":"allergens","label":"Alerjen bilgisi","value":[]},{"key":"origin","label":"Menşei","value":"Türkiye"},{"key":"nutrition","label":"Beslenme bildirimi (100 g/ml)","value":"Karışık içerik, ürün etiketlerine bakınız"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-gida' and p.name = 'Haftalık Sebze Sepeti';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"food","attributes":[{"key":"netQuantity","label":"Net miktar","value":"1 kg"},{"key":"unitPrice","label":"Birim fiyat","value":"45 TL/kg"},{"key":"allergens","label":"Alerjen bilgisi","value":[]},{"key":"origin","label":"Menşei","value":"Türkiye"},{"key":"nutrition","label":"Beslenme bildirimi (100 g/ml)","value":"Enerji 18 kcal, karbonhidrat 3,9 g, protein 0,9 g, tuz 0 g"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-gida' and p.name = 'Organik Domates (1 kg)';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"food","attributes":[{"key":"netQuantity","label":"Net miktar","value":"500 g"},{"key":"unitPrice","label":"Birim fiyat","value":"190 TL/kg"},{"key":"allergens","label":"Alerjen bilgisi","value":["Süt"]},{"key":"origin","label":"Menşei","value":"Türkiye"},{"key":"nutrition","label":"Beslenme bildirimi (100 g/ml)","value":"Enerji 264 kcal, yağ 21 g, protein 17 g, tuz 2,5 g"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-gida' and p.name = 'Köy Peyniri (500 gr)';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"food","attributes":[{"key":"netQuantity","label":"Net miktar","value":"500 g"},{"key":"unitPrice","label":"Birim fiyat","value":"150 TL/kg"},{"key":"allergens","label":"Alerjen bilgisi","value":[]},{"key":"origin","label":"Menşei","value":"Türkiye"},{"key":"nutrition","label":"Beslenme bildirimi (100 g/ml)","value":"Enerji 145 kcal, yağ 15 g, protein 1 g, tuz 3,3 g"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-gida' and p.name = 'Yöresel Zeytin Karma';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"food","attributes":[{"key":"netQuantity","label":"Net miktar","value":"400 g"},{"key":"unitPrice","label":"Birim fiyat","value":"137,50 TL/kg"},{"key":"allergens","label":"Alerjen bilgisi","value":[]},{"key":"origin","label":"Menşei","value":"Türkiye"},{"key":"nutrition","label":"Beslenme bildirimi (100 g/ml)","value":"Enerji 250 kcal, karbonhidrat 62 g, şeker 60 g, tuz 0 g"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-gida' and p.name = 'Çilek Reçeli (400 gr)';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"food","attributes":[{"key":"netQuantity","label":"Net miktar","value":"250 g"},{"key":"unitPrice","label":"Birim fiyat","value":"340 TL/kg"},{"key":"allergens","label":"Alerjen bilgisi","value":[]},{"key":"origin","label":"Menşei","value":"Türkiye"},{"key":"nutrition","label":"Beslenme bildirimi (100 g/ml)","value":"Enerji 213 kcal, yağ 18 g, karbonhidrat 9 g, tuz 1,2 g"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-gida' and p.name = 'Kuru Domates & Zeytinyağı';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"electronics","attributes":[{"key":"model","label":"Model","value":"Universal 6.1\""},{"key":"color","label":"Renk","value":"Şeffaf"},{"key":"compatibility","label":"Uyumluluk","value":"iPhone ve Samsung modelleri"},{"key":"warranty","label":"Garanti bilgisi","value":"Kırılmaya karşı 1 ay değişim"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'kiralik-teknik' and p.name = 'Temperli Cam Ekran Koruyucu';
update public.products p set metadata = '{"schemaVersion":4,"itemKind":"physical","templateKey":"electronics","attributes":[{"key":"model","label":"Model","value":"20W USB-C adaptör + kablo"},{"key":"color","label":"Renk","value":"Beyaz"},{"key":"compatibility","label":"Uyumluluk","value":"iPhone 8 ve üzeri"},{"key":"warranty","label":"Garanti bilgisi","value":"Üretici garantisi 24 ay"}]}'::jsonb from public.stores s where s.id = p.store_id and s.slug = 'demo-teknofix' and p.name = 'Orijinal Şarj Aleti & Kablo Seti';
